In [2]:
import numpy as np

In [3]:
n1=np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
n1

array([1, 2, 3, 4])

In [5]:
x=[]
len(dir(x))

47

In [6]:
len(dir(n1))

165

In [7]:
n1.shape # tells we have 4 values separated by commas.

(4,)

In [8]:
n2=np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


Creating matrix:-

arange
-linspace
-random.rand
-random.randn
-random.randint
-eye
-ones
-zeros

In [9]:
x=np.arange(-10,10,.2)
x.shape

(100,)

In [10]:
y=np.linspace(1,5,10)
print(y)
y.shape

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


(10,)

In [11]:
np.random.rand(3,3) # Gives random values between 0 and 1.

array([[0.98102529, 0.46997818, 0.15488451],
       [0.12894358, 0.85733822, 0.83447928],
       [0.30210351, 0.99214857, 0.5926226 ]])

In [12]:
np.random.randn(10)

array([ 0.08847692, -0.17552984,  0.78051282, -1.61371696, -0.6383868 ,
        0.32718446, -0.4337887 ,  0.1812104 , -1.08238986, -0.77132655])

In [13]:
np.random.randint(1,1000,(5,5)) # 5*5 matrix with random numbers between 1 and 1000.

array([[548,  37, 951, 600, 881],
       [782, 353, 981, 511, 790],
       [482, 614, 787, 992, 621],
       [382,  91, 839, 264, 160],
       [711, 877,  80, 216,  35]])

In [14]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(3,2))
print(x)
print(y)

[[8 9]
 [5 9]
 [3 6]]
[[2 3]
 [8 7]
 [9 7]]


In [15]:
x+5

array([[13, 14],
       [10, 14],
       [ 8, 11]])

In [16]:
x+y

array([[10, 12],
       [13, 16],
       [12, 13]])

In [17]:
x/y

array([[4.        , 3.        ],
       [0.625     , 1.28571429],
       [0.33333333, 0.85714286]])

In [18]:
x*y

array([[16, 27],
       [40, 63],
       [27, 42]])

In [19]:
x.dot(y.T) # Transpose of y matrix.

array([[ 43, 127, 135],
       [ 37, 103, 108],
       [ 24,  66,  69]])

In [20]:
np.sin(x)

array([[ 0.98935825,  0.41211849],
       [-0.95892427,  0.41211849],
       [ 0.14112001, -0.2794155 ]])

In [21]:
print(x.sum())
print(x.mean())
print(x.std())
print(x.min())
print(x.max())
print(x.var())

40
6.666666666666667
2.2110831935702664
3
9
4.888888888888888
