In [2]:
import numpy as np

In [3]:
n1=np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
n1

array([1, 2, 3, 4])

In [5]:
x=[]
len(dir(x))

47

In [6]:
len(dir(n1))

165

In [7]:
n1.shape # tells we have 4 values separated by commas.

(4,)

In [8]:
n2=np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


Creating matrix:-

arange
-linspace
-random.rand
-random.randn
-random.randint
-eye
-ones
-zeros

In [9]:
x=np.arange(-10,10,.2)
x.shape

(100,)

In [10]:
y=np.linspace(1,5,10)
print(y)
y.shape

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


(10,)

In [11]:
np.random.rand(3,3) # Gives random values between 0 and 1.

array([[0.46556649, 0.0385142 , 0.14977423],
       [0.37067571, 0.36870167, 0.94756893],
       [0.84474406, 0.95927589, 0.75422625]])

In [12]:
np.random.randn(10)

array([ 1.67641184, -0.13976249, -0.34628847,  0.63451106,  0.12601799,
        0.65611491, -0.89132017,  0.42593322, -0.54870077,  0.14396102])

In [13]:
np.random.randint(1,1000,(5,5)) # 5*5 matrix with random numbers between 1 and 1000.

array([[480, 948, 518, 543, 529],
       [923, 946,  51, 744, 342],
       [540, 465, 364, 464, 691],
       [978, 504, 423, 519, 175],
       [ 68, 535, 958, 434, 195]])

In [14]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(3,2))
print(x)
print(y)

[[8 4]
 [7 8]
 [7 9]]
[[8 8]
 [2 7]
 [5 8]]


In [15]:
x+5

array([[13,  9],
       [12, 13],
       [12, 14]])

In [16]:
x+y

array([[16, 12],
       [ 9, 15],
       [12, 17]])

In [17]:
x/y

array([[1.        , 0.5       ],
       [3.5       , 1.14285714],
       [1.4       , 1.125     ]])

In [18]:
x*y

array([[64, 32],
       [14, 56],
       [35, 72]])

In [19]:
x.dot(y.T) # Transpose of y matrix.

array([[ 96,  44,  72],
       [120,  70,  99],
       [128,  77, 107]])

In [20]:
np.sin(x)

array([[ 0.98935825, -0.7568025 ],
       [ 0.6569866 ,  0.98935825],
       [ 0.6569866 ,  0.41211849]])

In [21]:
print(x.sum())
print(x.mean())
print(x.std())
print(x.min())
print(x.max())
print(x.var())

43
7.166666666666667
1.5723301886761007
4
9
2.4722222222222228


In [22]:
a=np.linspace(0,5,50)
print(a.shape)
a2=a.reshape(10,5)
print(a2)
print(a2.shape)

(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]
(10, 5)


In [23]:
a2.reshape(5,5,2)  # 3D output.

array([[[0.        , 0.10204082],
        [0.20408163, 0.30612245],
        [0.40816327, 0.51020408],
        [0.6122449 , 0.71428571],
        [0.81632653, 0.91836735]],

       [[1.02040816, 1.12244898],
        [1.2244898 , 1.32653061],
        [1.42857143, 1.53061224],
        [1.63265306, 1.73469388],
        [1.83673469, 1.93877551]],

       [[2.04081633, 2.14285714],
        [2.24489796, 2.34693878],
        [2.44897959, 2.55102041],
        [2.65306122, 2.75510204],
        [2.85714286, 2.95918367]],

       [[3.06122449, 3.16326531],
        [3.26530612, 3.36734694],
        [3.46938776, 3.57142857],
        [3.67346939, 3.7755102 ],
        [3.87755102, 3.97959184]],

       [[4.08163265, 4.18367347],
        [4.28571429, 4.3877551 ],
        [4.48979592, 4.59183673],
        [4.69387755, 4.79591837],
        [4.89795918, 5.        ]]])

In [24]:
x=np.random.randint(1,10,(10,10))
print(x)

[[1 4 8 1 2 6 5 4 8 4]
 [9 1 5 8 4 5 7 8 9 6]
 [5 3 5 2 2 2 2 2 1 8]
 [7 7 6 5 8 1 9 2 1 2]
 [7 9 3 3 2 1 7 8 8 7]
 [8 5 4 1 3 6 7 7 4 5]
 [9 8 4 6 7 2 2 3 5 4]
 [7 7 9 7 4 2 8 7 6 5]
 [4 7 9 1 8 3 4 1 7 4]
 [2 4 6 6 2 5 8 2 2 3]]


In [25]:
print(x[0,0]) # first row first column
print(x[0,1]) # first row last column
print(x[-1,0]) # last row first column
print(x[-1,-1]) # last row last column

1
4
2
3


In [26]:
print(x[0]) # first row
print(x[1]) # second row
print(x[-1]) # last row
print(x[:3]) # first 3 rows
print(x[-3:]) # last 3 rows

[1 4 8 1 2 6 5 4 8 4]
[9 1 5 8 4 5 7 8 9 6]
[2 4 6 6 2 5 8 2 2 3]
[[1 4 8 1 2 6 5 4 8 4]
 [9 1 5 8 4 5 7 8 9 6]
 [5 3 5 2 2 2 2 2 1 8]]
[[7 7 9 7 4 2 8 7 6 5]
 [4 7 9 1 8 3 4 1 7 4]
 [2 4 6 6 2 5 8 2 2 3]]


In [27]:
print(x[:,0]) # first column
print(x[:,-1]) # last column
print(x[:,:3]) # first 3 column
print(x[:,-3:]) # last 3 column

[1 9 5 7 7 8 9 7 4 2]
[4 6 8 2 7 5 4 5 4 3]
[[1 4 8]
 [9 1 5]
 [5 3 5]
 [7 7 6]
 [7 9 3]
 [8 5 4]
 [9 8 4]
 [7 7 9]
 [4 7 9]
 [2 4 6]]
[[4 8 4]
 [8 9 6]
 [2 1 8]
 [2 1 2]
 [8 8 7]
 [7 4 5]
 [3 5 4]
 [7 6 5]
 [1 7 4]
 [2 2 3]]


In [28]:
print(x[:,[0,2,3,5]]) # will print 1st,3rd,4th and 6th column.

[[1 8 1 6]
 [9 5 8 5]
 [5 5 2 2]
 [7 6 5 1]
 [7 3 3 1]
 [8 4 1 6]
 [9 4 6 2]
 [7 9 7 2]
 [4 9 1 3]
 [2 6 6 5]]


In [29]:
x<5  # boolean filter.

array([[ True,  True, False,  True,  True, False, False,  True, False,
         True],
       [False,  True, False, False,  True, False, False, False, False,
        False],
       [False,  True, False,  True,  True,  True,  True,  True,  True,
        False],
       [False, False, False, False, False,  True, False,  True,  True,
         True],
       [False, False,  True,  True,  True,  True, False, False, False,
        False],
       [False, False,  True,  True,  True, False, False, False,  True,
        False],
       [False, False,  True, False, False,  True,  True,  True, False,
         True],
       [False, False, False, False,  True,  True, False, False, False,
        False],
       [ True, False, False,  True, False,  True,  True,  True, False,
         True],
       [ True,  True, False, False,  True, False, False,  True,  True,
         True]])

In [30]:
x[x<5]

array([1, 4, 1, 2, 4, 4, 1, 4, 3, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 3, 3, 2,
       1, 4, 1, 3, 4, 4, 2, 2, 3, 4, 4, 2, 4, 1, 3, 4, 1, 4, 2, 4, 2, 2,
       2, 3])

In [31]:
x[x>5]

array([8, 6, 8, 9, 8, 7, 8, 9, 6, 8, 7, 7, 6, 8, 9, 7, 9, 7, 8, 8, 7, 8,
       6, 7, 7, 9, 8, 6, 7, 7, 7, 9, 7, 8, 7, 6, 7, 9, 8, 7, 6, 6, 8])

In [32]:
x[(x>=3) & (x<=6)]

array([4, 6, 5, 4, 4, 5, 4, 5, 6, 5, 3, 5, 6, 5, 3, 3, 5, 4, 3, 6, 4, 5,
       4, 6, 3, 5, 4, 4, 6, 5, 4, 3, 4, 4, 4, 6, 6, 5, 3])

In [33]:
x[x>5].sum()

320