In [1]:
import numpy as np

In [2]:
n1=np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
n1

array([1, 2, 3, 4])

In [4]:
x=[]
len(dir(x))

47

In [5]:
len(dir(n1))

165

In [6]:
n1.shape # tells we have 4 values separated by commas.

(4,)

In [7]:
n2=np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


Creating matrix:-

arange
-linspace
-random.rand
-random.randn
-random.randint
-eye
-ones
-zeros

In [8]:
x=np.arange(-10,10,.2)
x.shape

(100,)

In [9]:
y=np.linspace(1,5,10)
print(y)
y.shape

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


(10,)

In [10]:
np.random.rand(3,3) # Gives random values between 0 and 1.

array([[0.65449192, 0.80740796, 0.70684761],
       [0.17046495, 0.91220863, 0.06470097],
       [0.02499474, 0.70437663, 0.24798706]])

In [11]:
np.random.randn(10)

array([ 0.49654257,  2.050194  , -0.6202102 , -0.33001044, -0.25230285,
       -0.85904795, -0.88220268,  0.63445297,  0.25121027,  0.03234024])

In [12]:
np.random.randint(1,1000,(5,5)) # 5*5 matrix with random numbers between 1 and 1000.

array([[244, 431,  68, 317,  27],
       [812, 167, 197, 613, 596],
       [713, 352, 326, 433, 703],
       [951, 852, 463, 843, 396],
       [108, 607, 998, 371, 886]])

In [13]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(3,2))
print(x)
print(y)

[[3 8]
 [7 5]
 [8 2]]
[[2 6]
 [4 3]
 [7 3]]


In [14]:
x+5

array([[ 8, 13],
       [12, 10],
       [13,  7]])

In [15]:
x+y

array([[ 5, 14],
       [11,  8],
       [15,  5]])

In [16]:
x/y

array([[1.5       , 1.33333333],
       [1.75      , 1.66666667],
       [1.14285714, 0.66666667]])

In [17]:
x*y

array([[ 6, 48],
       [28, 15],
       [56,  6]])

In [18]:
x.dot(y.T) # Transpose of y matrix.

array([[54, 36, 45],
       [44, 43, 64],
       [28, 38, 62]])

In [19]:
np.sin(x)

array([[ 0.14112001,  0.98935825],
       [ 0.6569866 , -0.95892427],
       [ 0.98935825,  0.90929743]])

In [20]:
print(x.sum())
print(x.mean())
print(x.std())
print(x.min())
print(x.max())
print(x.var())

33
5.5
2.362907813126304
2
8
5.583333333333333


In [21]:
a=np.linspace(0,5,50)
print(a.shape)
a2=a.reshape(10,5)
print(a2)
print(a2.shape)

(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]
(10, 5)


In [22]:
a2.reshape(5,5,2)  # 3D output.

array([[[0.        , 0.10204082],
        [0.20408163, 0.30612245],
        [0.40816327, 0.51020408],
        [0.6122449 , 0.71428571],
        [0.81632653, 0.91836735]],

       [[1.02040816, 1.12244898],
        [1.2244898 , 1.32653061],
        [1.42857143, 1.53061224],
        [1.63265306, 1.73469388],
        [1.83673469, 1.93877551]],

       [[2.04081633, 2.14285714],
        [2.24489796, 2.34693878],
        [2.44897959, 2.55102041],
        [2.65306122, 2.75510204],
        [2.85714286, 2.95918367]],

       [[3.06122449, 3.16326531],
        [3.26530612, 3.36734694],
        [3.46938776, 3.57142857],
        [3.67346939, 3.7755102 ],
        [3.87755102, 3.97959184]],

       [[4.08163265, 4.18367347],
        [4.28571429, 4.3877551 ],
        [4.48979592, 4.59183673],
        [4.69387755, 4.79591837],
        [4.89795918, 5.        ]]])

In [23]:
x=np.random.randint(1,10,(10,10))
print(x)

[[7 1 8 2 2 3 8 2 9 2]
 [2 9 6 2 2 4 8 4 4 6]
 [2 3 5 7 3 4 8 4 3 9]
 [3 5 9 6 2 2 4 1 1 9]
 [5 6 9 4 2 3 7 5 5 1]
 [1 5 1 1 2 8 6 4 4 9]
 [3 7 1 2 5 1 7 9 9 4]
 [1 2 6 2 9 4 9 2 9 1]
 [1 8 5 4 7 2 8 3 1 7]
 [6 8 1 3 5 1 8 4 4 5]]


In [24]:
print(x[0,0]) # first row first column
print(x[0,1]) # first row last column
print(x[-1,0]) # last row first column
print(x[-1,-1]) # last row last column

7
1
6
5


In [25]:
print(x[0]) # first row
print(x[1]) # second row
print(x[-1]) # last row
print(x[:3]) # first 3 rows
print(x[-3:]) # last 3 rows

[7 1 8 2 2 3 8 2 9 2]
[2 9 6 2 2 4 8 4 4 6]
[6 8 1 3 5 1 8 4 4 5]
[[7 1 8 2 2 3 8 2 9 2]
 [2 9 6 2 2 4 8 4 4 6]
 [2 3 5 7 3 4 8 4 3 9]]
[[1 2 6 2 9 4 9 2 9 1]
 [1 8 5 4 7 2 8 3 1 7]
 [6 8 1 3 5 1 8 4 4 5]]


In [26]:
print(x[:,0]) # first column
print(x[:,-1]) # last column
print(x[:,:3]) # first 3 column
print(x[:,-3:]) # last 3 column

[7 2 2 3 5 1 3 1 1 6]
[2 6 9 9 1 9 4 1 7 5]
[[7 1 8]
 [2 9 6]
 [2 3 5]
 [3 5 9]
 [5 6 9]
 [1 5 1]
 [3 7 1]
 [1 2 6]
 [1 8 5]
 [6 8 1]]
[[2 9 2]
 [4 4 6]
 [4 3 9]
 [1 1 9]
 [5 5 1]
 [4 4 9]
 [9 9 4]
 [2 9 1]
 [3 1 7]
 [4 4 5]]


In [27]:
print(x[:,[0,2,3,5]]) # will print 1st,3rd,4th and 6th column.

[[7 8 2 3]
 [2 6 2 4]
 [2 5 7 4]
 [3 9 6 2]
 [5 9 4 3]
 [1 1 1 8]
 [3 1 2 1]
 [1 6 2 4]
 [1 5 4 2]
 [6 1 3 1]]


In [28]:
x<5  # boolean filter.

array([[False,  True, False,  True,  True,  True, False,  True, False,
         True],
       [ True, False, False,  True,  True,  True, False,  True,  True,
        False],
       [ True,  True, False, False,  True,  True, False,  True,  True,
        False],
       [ True, False, False, False,  True,  True,  True,  True,  True,
        False],
       [False, False, False,  True,  True,  True, False, False, False,
         True],
       [ True, False,  True,  True,  True, False, False,  True,  True,
        False],
       [ True, False,  True,  True, False,  True, False, False, False,
         True],
       [ True,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False, False,  True, False,  True, False,  True,  True,
        False],
       [False, False,  True,  True, False,  True, False,  True,  True,
        False]])

In [29]:
x[x<5]

array([1, 2, 2, 3, 2, 2, 2, 2, 2, 4, 4, 4, 2, 3, 3, 4, 4, 3, 3, 2, 2, 4,
       1, 1, 4, 2, 3, 1, 1, 1, 1, 2, 4, 4, 3, 1, 2, 1, 4, 1, 2, 2, 4, 2,
       1, 1, 4, 2, 3, 1, 1, 3, 1, 4, 4])

In [30]:
x[x>5]

array([7, 8, 8, 9, 9, 6, 8, 6, 7, 8, 9, 9, 6, 9, 6, 9, 7, 8, 6, 9, 7, 7,
       9, 9, 6, 9, 9, 9, 8, 7, 8, 7, 6, 8, 8])

In [31]:
x[(x>=3) & (x<=6)]

array([3, 6, 4, 4, 4, 6, 3, 5, 3, 4, 4, 3, 3, 5, 6, 4, 5, 6, 4, 3, 5, 5,
       5, 6, 4, 4, 3, 5, 4, 6, 4, 5, 4, 3, 6, 3, 5, 4, 4, 5])

In [32]:
x[x>5].sum()

271